spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CareerPath;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysupersecretkeymysupersecretkey123456
jwt.expiration=3600000

google.client.id=532793804448-3dubvn91hg0aqui4j7o0r967tg7pgrkf.apps.googleusercontent.com
gemini.api.key=AIzaSyADdUI-dJN1XHwi8AjlyKtZFZ63wlKpCUY
gemini.model=gemini-2.5-flash

cloudinary.cloud-name=dsbhtgduv
cloudinary.api-key=464182592329662
cloudinary.api-secret=mVpFBXQdPj887ex6GYDbiZQhP9M
    
