package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final



/**
 * BookingStatuses generated by hbm2java
 */
public class BookingStatuses  implements java.io.Serializable {


     private Integer statusId;
     private String name;

    public BookingStatuses() {
    }

    public BookingStatuses(String name) {
       this.name = name;
    }
   
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


