package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Careers generated by hbm2java
 */
@Entity
@Table(name = "careers")
public class Careers  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "career_id")
     private Integer careerId;

     @Column(name = "name")
     private String name;

     @Column(name = "description")
     private String description;

     @Column(name = "min_salary")
     private BigDecimal min_salary;

     @Column(name = "max_salary")
     private BigDecimal max_salary;

     @Column(name = "demand_level")
     private Integer demandLevel;

     @Column(name = "image")
     private String image;  

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "careers")
     private Set<CareerFactors> careerFactorses = new HashSet<>(0);

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "careers")
     private Set<CareerSkills> careerSkillses = new HashSet<>(0);

    public Careers() {
    }

    public Careers(String name, String description, BigDecimal min_salary, BigDecimal max_salary, Integer demandLevel, Set<CareerFactors> careerFactorses, Set<CareerSkills> careerSkillses) {
       this.name = name;
       this.description = description;
       this.min_salary = min_salary;
       this.max_salary = max_salary;
       this.demandLevel = demandLevel;
       this.careerFactorses = careerFactorses;
       this.careerSkillses = careerSkillses;
    }
   
    public Integer getCareerId() {
        return this.careerId;
    }
    
    public void setCareerId(Integer careerId) {
        this.careerId = careerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getMinSalary() {
        return this.min_salary;
    }

    public void setMinSalary(BigDecimal min_salary) {
        this.min_salary = min_salary;
    }

    public BigDecimal getMaxSalary() {
        return this.max_salary;
    }

    public void setMaxSalary(BigDecimal max_salary) {
        this.max_salary = max_salary;
    }
    public Integer getDemandLevel() {
        return this.demandLevel;
    }
    
    public void setDemandLevel(Integer demandLevel) {
        this.demandLevel = demandLevel;
    }
    public Set<CareerFactors> getCareerFactorses() {
        return this.careerFactorses;
    }
    
    public void setCareerFactorses(Set<CareerFactors> careerFactorses) {
        this.careerFactorses = careerFactorses;
    }
    public Set<CareerSkills> getCareerSkillses() {
        return this.careerSkillses;
    }
    
    public void setCareerSkillses(Set<CareerSkills> careerSkillses) {
        this.careerSkillses = careerSkillses;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

}


