package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * CareerFactors generated by hbm2java
 */
@Entity
@Table(name = "career_factors")
public class CareerFactors  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id")
     private Integer id;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "career_id")
     private Careers careers;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "factor_id")
     private Factors factors;

     @Column(name = "weight")
     private BigDecimal weight;

    public CareerFactors() {
    }

    public CareerFactors(Careers careers, Factors factors, BigDecimal weight) {
       this.careers = careers;
       this.factors = factors;
       this.weight = weight;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Careers getCareers() {
        return this.careers;
    }
    
    public void setCareers(Careers careers) {
        this.careers = careers;
    }
    public Factors getFactors() {
        return this.factors;
    }
    
    public void setFactors(Factors factors) {
        this.factors = factors;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }




}


