package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Careers generated by hbm2java
 */
public class Careers  implements java.io.Serializable {


     private Integer careerId;
     private String name;
     private Serializable description;
     private BigDecimal avgSalary;
     private Integer demandLevel;
     private Set careerFactorses = new HashSet(0);
     private Set careerSkillses = new HashSet(0);

    public Careers() {
    }

    public Careers(String name, Serializable description, BigDecimal avgSalary, Integer demandLevel, Set careerFactorses, Set careerSkillses) {
       this.name = name;
       this.description = description;
       this.avgSalary = avgSalary;
       this.demandLevel = demandLevel;
       this.careerFactorses = careerFactorses;
       this.careerSkillses = careerSkillses;
    }
   
    public Integer getCareerId() {
        return this.careerId;
    }
    
    public void setCareerId(Integer careerId) {
        this.careerId = careerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public BigDecimal getAvgSalary() {
        return this.avgSalary;
    }
    
    public void setAvgSalary(BigDecimal avgSalary) {
        this.avgSalary = avgSalary;
    }
    public Integer getDemandLevel() {
        return this.demandLevel;
    }
    
    public void setDemandLevel(Integer demandLevel) {
        this.demandLevel = demandLevel;
    }
    public Set getCareerFactorses() {
        return this.careerFactorses;
    }
    
    public void setCareerFactorses(Set careerFactorses) {
        this.careerFactorses = careerFactorses;
    }
    public Set getCareerSkillses() {
        return this.careerSkillses;
    }
    
    public void setCareerSkillses(Set careerSkillses) {
        this.careerSkillses = careerSkillses;
    }




}


