package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.math.BigDecimal;

/**
 * CareerFactors generated by hbm2java
 */
public class CareerFactors  implements java.io.Serializable {


     private Integer id;
     private Careers careers;
     private Factors factors;
     private BigDecimal weight;

    public CareerFactors() {
    }

    public CareerFactors(Careers careers, Factors factors, BigDecimal weight) {
       this.careers = careers;
       this.factors = factors;
       this.weight = weight;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Careers getCareers() {
        return this.careers;
    }
    
    public void setCareers(Careers careers) {
        this.careers = careers;
    }
    public Factors getFactors() {
        return this.factors;
    }
    
    public void setFactors(Factors factors) {
        this.factors = factors;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }




}


