package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * CareerSkills generated by hbm2java
 */
@Entity
@Table(name = "career_skills")
public class CareerSkills  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id")
     private Integer id;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "career_id")
     private Careers careers;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "skill_id")
     private Skills skills;

     @Column(name = "weight")
     private BigDecimal weight;

    public CareerSkills() {
    }

    public CareerSkills(Careers careers, Skills skills, BigDecimal weight) {
       this.careers = careers;
       this.skills = skills;
       this.weight = weight;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Careers getCareers() {
        return this.careers;
    }
    
    public void setCareers(Careers careers) {
        this.careers = careers;
    }
    public Skills getSkills() {
        return this.skills;
    }
    
    public void setSkills(Skills skills) {
        this.skills = skills;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }




}


