package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Choices generated by hbm2java
 */
public class Choices  implements java.io.Serializable {


     private Integer choiceId;
     private Questions questions;
     private Serializable content;
     private Integer scoreValue;
     private Set userAnswerses = new HashSet(0);

    public Choices() {
    }

    public Choices(Questions questions, Serializable content, Integer scoreValue, Set userAnswerses) {
       this.questions = questions;
       this.content = content;
       this.scoreValue = scoreValue;
       this.userAnswerses = userAnswerses;
    }
   
    public Integer getChoiceId() {
        return this.choiceId;
    }
    
    public void setChoiceId(Integer choiceId) {
        this.choiceId = choiceId;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public Serializable getContent() {
        return this.content;
    }
    
    public void setContent(Serializable content) {
        this.content = content;
    }
    public Integer getScoreValue() {
        return this.scoreValue;
    }
    
    public void setScoreValue(Integer scoreValue) {
        this.scoreValue = scoreValue;
    }
    public Set getUserAnswerses() {
        return this.userAnswerses;
    }
    
    public void setUserAnswerses(Set userAnswerses) {
        this.userAnswerses = userAnswerses;
    }




}


