package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Choices generated by hbm2java
 */
@Entity
@Table(name = "choices")
public class Choices  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "choice_id")
     private Integer choiceId;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "question_id")
     private Questions questions;

     @Column(name = "content")
     private Serializable content;

     @Column(name = "score_value")
     private Integer scoreValue;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "choices")
     private Set userAnswerses = new HashSet(0);

    public Choices() {
    }

    public Choices(Questions questions, Serializable content, Integer scoreValue, Set userAnswerses) {
       this.questions = questions;
       this.content = content;
       this.scoreValue = scoreValue;
       this.userAnswerses = userAnswerses;
    }
   
    public Integer getChoiceId() {
        return this.choiceId;
    }
    
    public void setChoiceId(Integer choiceId) {
        this.choiceId = choiceId;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public Serializable getContent() {
        return this.content;
    }
    
    public void setContent(Serializable content) {
        this.content = content;
    }
    public Integer getScoreValue() {
        return this.scoreValue;
    }
    
    public void setScoreValue(Integer scoreValue) {
        this.scoreValue = scoreValue;
    }
    public Set getUserAnswerses() {
        return this.userAnswerses;
    }
    
    public void setUserAnswerses(Set userAnswerses) {
        this.userAnswerses = userAnswerses;
    }




}


