package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final



/**
 * CourseLevels generated by hbm2java
 */
public class CourseLevels  implements java.io.Serializable {


     private Integer levelId;
     private String name;

    public CourseLevels() {
    }

    public CourseLevels(String name) {
       this.name = name;
    }
   
    public Integer getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


