package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final



/**
 * Degrees generated by hbm2java
 */
import jakarta.persistence.*;

@Entity
@Table(name = "degrees")
public class Degrees  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "degree_id")
     private Integer degreeId;

     @Column(name = "name")
     private String name;

    public Degrees() {
    }

    public Degrees(String name) {
       this.name = name;
    }
   
    public Integer getDegreeId() {
        return this.degreeId;
    }
    
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


