package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * FactorTypes generated by hbm2java
 */
public class FactorTypes  implements java.io.Serializable {


     private Integer typeId;
     private String name;
     private Set factorses = new HashSet(0);

    public FactorTypes() {
    }

    public FactorTypes(String name, Set factorses) {
       this.name = name;
       this.factorses = factorses;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getFactorses() {
        return this.factorses;
    }
    
    public void setFactorses(Set factorses) {
        this.factorses = factorses;
    }




}


