package com.example.CareerPath_BE.entities;

import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * FactorTypes generated by hbm2java
 */
@Entity
@Table(name = "factor_types")
public class FactorTypes  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "type_id")
     private Integer typeId;

     @Column(name = "name")
     private String name;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "factorTypes")
     private Set<Factors> factorses = new HashSet<>(0);

    public FactorTypes() {
    }

    public FactorTypes(String name, Set<Factors> factorses) {
       this.name = name;
       this.factorses = factorses;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Factors> getFactorses() {
        return this.factorses;
    }
    
    public void setFactorses(Set<Factors> factorses) {
        this.factorses = factorses;
    }




}


