package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Factors generated by hbm2java
 */
public class Factors  implements java.io.Serializable {


     private Integer factorId;
     private FactorTypes factorTypes;
     private String name;
     private Set questionFactorses = new HashSet(0);
     private Set careerFactorses = new HashSet(0);

    public Factors() {
    }

    public Factors(FactorTypes factorTypes, String name, Set questionFactorses, Set careerFactorses) {
       this.factorTypes = factorTypes;
       this.name = name;
       this.questionFactorses = questionFactorses;
       this.careerFactorses = careerFactorses;
    }
   
    public Integer getFactorId() {
        return this.factorId;
    }
    
    public void setFactorId(Integer factorId) {
        this.factorId = factorId;
    }
    public FactorTypes getFactorTypes() {
        return this.factorTypes;
    }
    
    public void setFactorTypes(FactorTypes factorTypes) {
        this.factorTypes = factorTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getQuestionFactorses() {
        return this.questionFactorses;
    }
    
    public void setQuestionFactorses(Set questionFactorses) {
        this.questionFactorses = questionFactorses;
    }
    public Set getCareerFactorses() {
        return this.careerFactorses;
    }
    
    public void setCareerFactorses(Set careerFactorses) {
        this.careerFactorses = careerFactorses;
    }




}


