package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Genders generated by hbm2java
 */
public class Genders  implements java.io.Serializable {


     private Integer genderId;
     private String name;
     private Set userProfileses = new HashSet(0);

    public Genders() {
    }

    public Genders(String name, Set userProfileses) {
       this.name = name;
       this.userProfileses = userProfileses;
    }
   
    public Integer getGenderId() {
        return this.genderId;
    }
    
    public void setGenderId(Integer genderId) {
        this.genderId = genderId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserProfileses() {
        return this.userProfileses;
    }
    
    public void setUserProfileses(Set userProfileses) {
        this.userProfileses = userProfileses;
    }




}


