package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.math.BigDecimal;

/**
 * QuestionFactors generated by hbm2java
 */
public class QuestionFactors  implements java.io.Serializable {


     private Integer id;
     private Factors factors;
     private Questions questions;
     private BigDecimal weight;

    public QuestionFactors() {
    }

    public QuestionFactors(Factors factors, Questions questions, BigDecimal weight) {
       this.factors = factors;
       this.questions = questions;
       this.weight = weight;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Factors getFactors() {
        return this.factors;
    }
    
    public void setFactors(Factors factors) {
        this.factors = factors;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }




}


