package com.example.CareerPath_BE.entities;

import jakarta.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions")
public class Questions  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "question_id")
     private Integer questionId;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "test_id")
     private Tests tests;

     @Column(name = "content")
     private Serializable content;

     @Column(name = "dimension")
     private String dimension;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
     private Set choiceses = new HashSet(0);

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
     private Set userAnswerses = new HashSet(0);

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "questions")
     private Set questionFactorses = new HashSet(0);

    public Questions() {
    }

    public Questions(Tests tests, Serializable content, String dimension, Set choiceses, Set userAnswerses, Set questionFactorses) {
       this.tests = tests;
       this.content = content;
       this.dimension = dimension;
       this.choiceses = choiceses;
       this.userAnswerses = userAnswerses;
       this.questionFactorses = questionFactorses;
    }
   
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public Tests getTests() {
        return this.tests;
    }
    
    public void setTests(Tests tests) {
        this.tests = tests;
    }
    public Serializable getContent() {
        return this.content;
    }
    
    public void setContent(Serializable content) {
        this.content = content;
    }
    public String getDimension() {
        return this.dimension;
    }
    
    public void setDimension(String dimension) {
        this.dimension = dimension;
    }
    public Set getChoiceses() {
        return this.choiceses;
    }
    
    public void setChoiceses(Set choiceses) {
        this.choiceses = choiceses;
    }
    public Set getUserAnswerses() {
        return this.userAnswerses;
    }
    
    public void setUserAnswerses(Set userAnswerses) {
        this.userAnswerses = userAnswerses;
    }
    public Set getQuestionFactorses() {
        return this.questionFactorses;
    }
    
    public void setQuestionFactorses(Set questionFactorses) {
        this.questionFactorses = questionFactorses;
    }




}


