package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * QuestionFactors generated by hbm2java
 */
@Entity
@Table(name = "question_factors")
public class QuestionFactors  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "id")
     private Integer id;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "factor_id")
     private Factors factors;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "question_id")
     private Questions questions;

     @Column(name = "weight")
     private BigDecimal weight;

    public QuestionFactors() {
    }

    public QuestionFactors(Factors factors, Questions questions, BigDecimal weight) {
       this.factors = factors;
       this.questions = questions;
       this.weight = weight;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Factors getFactors() {
        return this.factors;
    }
    
    public void setFactors(Factors factors) {
        this.factors = factors;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }




}


