package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final



/**
 * RoadmapItemTypes generated by hbm2java
 */
public class RoadmapItemTypes  implements java.io.Serializable {


     private Integer typeId;
     private String name;

    public RoadmapItemTypes() {
    }

    public RoadmapItemTypes(String name) {
       this.name = name;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


