package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles")
public class Roles  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "role_id")
     private Integer roleId;

     @Column(name = "name")
     private String name;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
     private Set userses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String name) {
        this.name = name;
    }
    public Roles(String name, Set userses) {
       this.name = name;
       this.userses = userses;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


