package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Skills generated by hbm2java
 */
public class Skills  implements java.io.Serializable {


     private Integer skillId;
     private String name;
     private String type;
     private Set careerSkillses = new HashSet(0);

    public Skills() {
    }

    public Skills(String name, String type, Set careerSkillses) {
       this.name = name;
       this.type = type;
       this.careerSkillses = careerSkillses;
    }
   
    public Integer getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getCareerSkillses() {
        return this.careerSkillses;
    }
    
    public void setCareerSkillses(Set careerSkillses) {
        this.careerSkillses = careerSkillses;
    }




}


