package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Skills generated by hbm2java
 */
@Entity
@Table(name = "skills")
public class Skills  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "skill_id")
     private Integer skillId;

     @Column(name = "name")
     private String name;

     @Column(name = "type")
     private String type;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
     private Set careerSkillses = new HashSet(0);

    public Skills() {
    }

    public Skills(String name, String type, Set careerSkillses) {
       this.name = name;
       this.type = type;
       this.careerSkillses = careerSkillses;
    }
   
    public Integer getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getCareerSkillses() {
        return this.careerSkillses;
    }
    
    public void setCareerSkillses(Set careerSkillses) {
        this.careerSkillses = careerSkillses;
    }




}


