package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tests generated by hbm2java
 */
public class Tests  implements java.io.Serializable {


     private Integer testId;
     private TestTypes testTypes;
     private String name;
     private Set questionses = new HashSet(0);

    public Tests() {
    }

    public Tests(TestTypes testTypes, String name, Set questionses) {
       this.testTypes = testTypes;
       this.name = name;
       this.questionses = questionses;
    }
   
    public Integer getTestId() {
        return this.testId;
    }
    
    public void setTestId(Integer testId) {
        this.testId = testId;
    }
    public TestTypes getTestTypes() {
        return this.testTypes;
    }
    
    public void setTestTypes(TestTypes testTypes) {
        this.testTypes = testTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set questionses) {
        this.questionses = questionses;
    }




}


