package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * TestTypes generated by hbm2java
 */
@Entity
@Table(name = "test_types")
public class TestTypes  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "test_type_id")
     private Integer typeId;

     @Column(name = "name")
     private String name;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "testTypes")
     private Set testses = new HashSet(0);

    public TestTypes() {
    }

    public TestTypes(String name, Set testses) {
       this.name = name;
       this.testses = testses;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTestses() {
        return this.testses;
    }
    
    public void setTestses(Set testses) {
        this.testses = testses;
    }




}


