package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TestTypes generated by hbm2java
 */
public class TestTypes  implements java.io.Serializable {


     private Integer typeId;
     private String name;
     private Set testses = new HashSet(0);

    public TestTypes() {
    }

    public TestTypes(String name, Set testses) {
       this.name = name;
       this.testses = testses;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTestses() {
        return this.testses;
    }
    
    public void setTestses(Set testses) {
        this.testses = testses;
    }




}


