package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final



/**
 * TestDimensions generated by hbm2java
 */
public class TestDimensions  implements java.io.Serializable {


     private Integer dimensionId;
     private String name;

    public TestDimensions() {
    }

    public TestDimensions(String name) {
       this.name = name;
    }
   
    public Integer getDimensionId() {
        return this.dimensionId;
    }
    
    public void setDimensionId(Integer dimensionId) {
        this.dimensionId = dimensionId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


