package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final



/**
 * UserAnswers generated by hbm2java
 */
public class UserAnswers  implements java.io.Serializable {


     private Integer answerId;
     private Choices choices;
     private Questions questions;
     private Users users;

    public UserAnswers() {
    }

    public UserAnswers(Choices choices, Questions questions, Users users) {
       this.choices = choices;
       this.questions = questions;
       this.users = users;
    }
   
    public Integer getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }
    public Choices getChoices() {
        return this.choices;
    }
    
    public void setChoices(Choices choices) {
        this.choices = choices;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


