package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.io.Serializable;
import java.util.Date;

/**
 * UserProfiles generated by hbm2java
 */
public class UserProfiles  implements java.io.Serializable {


     private Integer profileId;
     private Genders genders;
     private Users users;
     private Date dateOfBirth;
     private String school;
     private Integer grade;
     private Serializable bio;

    public UserProfiles() {
    }

    public UserProfiles(Genders genders, Users users, Date dateOfBirth, String school, Integer grade, Serializable bio) {
       this.genders = genders;
       this.users = users;
       this.dateOfBirth = dateOfBirth;
       this.school = school;
       this.grade = grade;
       this.bio = bio;
    }
   
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    public Genders getGenders() {
        return this.genders;
    }
    
    public void setGenders(Genders genders) {
        this.genders = genders;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public Integer getGrade() {
        return this.grade;
    }
    
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
    public Serializable getBio() {
        return this.bio;
    }
    
    public void setBio(Serializable bio) {
        this.bio = bio;
    }




}


