package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:15:08 by Hibernate Tools 5.6.15.Final


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private Roles roles;
     private String email;
     private Serializable passwordHash;
     private String fullName;
     private Date createdAt;
     private Set userProfileses = new HashSet(0);
     private Set userAnswerses = new HashSet(0);

    public Users() {
    }

	
    public Users(String email, Serializable passwordHash) {
        this.email = email;
        this.passwordHash = passwordHash;
    }
    public Users(Roles roles, String email, Serializable passwordHash, String fullName, Date createdAt, Set userProfileses, Set userAnswerses) {
       this.roles = roles;
       this.email = email;
       this.passwordHash = passwordHash;
       this.fullName = fullName;
       this.createdAt = createdAt;
       this.userProfileses = userProfileses;
       this.userAnswerses = userAnswerses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Serializable getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(Serializable passwordHash) {
        this.passwordHash = passwordHash;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getUserProfileses() {
        return this.userProfileses;
    }
    
    public void setUserProfileses(Set userProfileses) {
        this.userProfileses = userProfileses;
    }
    public Set getUserAnswerses() {
        return this.userAnswerses;
    }
    
    public void setUserAnswerses(Set userAnswerses) {
        this.userAnswerses = userAnswerses;
    }




}


