package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * UserProfiles generated by hbm2java
 */
@Entity
@Table(name = "user_profiles")
public class UserProfiles  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "profile_id")
     private Integer profileId;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "gender_id")
     private Genders genders;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "user_id")
     private Users users;

     @Column(name = "date_of_birth")
     private Date dateOfBirth;

     @Column(name = "school")
     private String school;

     @Column(name = "grade")
     private Integer grade;

     @Column(name = "bio")
     private String bio;

     @Column(name = "address")
     private String address;

     @Column(name = "image")
     private String image;  

    public UserProfiles() {
    }

    public UserProfiles(Genders genders, Users users, Date dateOfBirth, String school, Integer grade, String bio, String address, String image) {
       this.genders = genders;
       this.users = users;
       this.dateOfBirth = dateOfBirth;
       this.school = school;
       this.grade = grade;
       this.bio = bio;
       this.address = address;
       this.image = image;
    }
   
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }
    public Genders getGenders() {
        return this.genders;
    }
    
    public void setGenders(Genders genders) {
        this.genders = genders;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getSchool() {
        return this.school;
    }
    
    public void setSchool(String school) {
        this.school = school;
    }
    public Integer getGrade() {
        return this.grade;
    }
    
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }
    public String getImage() {
        return this.image;
    }
    public void setImage(String image) {
        this.image = image;
    }
    public String getAddress() {
        return this.address;
    }
    public void setAddress(String address) {
        this.address = address;
    }

}


