package com.example.CareerPath_BE.entities;
// Generated 20 Apr 2026, 02:31:16 by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users  implements java.io.Serializable {


     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     @Column(name = "user_id")
     private Integer userId;

     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name = "role_id")
     private Roles roles;

     @Column(name = "email", unique = true, nullable = false)
     private String email;

     @Column(name = "password_hash")
     private Serializable passwordHash;

     @Column(name = "full_name")
     private String fullName;

     @Column(name = "created_at")
     private Date createdAt;

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
     private Set userProfileses = new HashSet(0);

     @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
     private Set userAnswerses = new HashSet(0);

    public Users() {
    }

	
    public Users(String email, Serializable passwordHash) {
        this.email = email;
        this.passwordHash = passwordHash;
    }
    public Users(Roles roles, String email, Serializable passwordHash, String fullName, Date createdAt, Set userProfileses, Set userAnswerses) {
       this.roles = roles;
       this.email = email;
       this.passwordHash = passwordHash;
       this.fullName = fullName;
       this.createdAt = createdAt;
       this.userProfileses = userProfileses;
       this.userAnswerses = userAnswerses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Serializable getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(Serializable passwordHash) {
        this.passwordHash = passwordHash;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getUserProfileses() {
        return this.userProfileses;
    }
    
    public void setUserProfileses(Set userProfileses) {
        this.userProfileses = userProfileses;
    }
    public Set getUserAnswerses() {
        return this.userAnswerses;
    }
    
    public void setUserAnswerses(Set userAnswerses) {
        this.userAnswerses = userAnswerses;
    }




}


